$(document).ready(function(){
    $('.seven').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:3,
                nav:true
            },
            1000:{
                items:7,
                nav:true,
                loop:true
            }
        }
    })
  });